name: testing
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.0
  google_sign_in:
  google_maps_flutter: ^0.5.26+2
  cloud_firestore: ^0.13.4+2
  firebase_storage: ^3.1.5
  geoflutterfire: ^2.0.2
  rxdart: ^0.22.0
  geolocator: any
  flare_flutter: any
  flutter_emoji: ">= 2.0.0"
  demoji: ^1.0.1
  google_fonts: ^1.0.0
  font_awesome_flutter: ^8.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/work.flr
    - assets/google_logo.png
    - assets/searching.flr
    - assets/Checkbox.flr
    - assets/Giftbox.flr
    - assets/Success Check.flr
